name:                delphi
version:             0.1.0.0
github:              "arafangion/delphiparser"
license:             BSD3
author:              "John Chapman"
maintainer:          "delphi@fussycoder.id.au"
copyright:           "2018 John Chapman"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/delphi#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - text
  - hex
  - safe
  - pretty-simple
  - megaparsec
  ghc-options:
  - -Wall
#  - -O0

executables:
  delphi-docs:
    main: Main.hs
    source-dirs: delphi-docs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
#    - -O0
    dependencies:
    - delphi
    - text
    - megaparsec
    - directory
    - filepath
    - bytestring
    - monad-parallel
    - yesod
  delphi-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
#    - -O0
    dependencies:
    - delphi
    - text
    - megaparsec
    - directory
    - filepath
    - bytestring
    - monad-parallel

tests:
  delphi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O0
    dependencies:
    - text
    - delphi
    - tasty
    - tasty-hunit
    - megaparsec
